import 'package:flutter_test/flutter_test.dart';
import 'package:zikzak_inappwebview/zikzak_inappwebview.dart';

void main() {
  group('SelectorCandidateRules.looksAutoGeneratedId', () {
    test('uuid-ish ids are auto-generated', () {
      expect(
        SelectorCandidateRules.looksAutoGeneratedId(
          '550e8400-e29b-41d4-a716-446655440000',
        ),
        isTrue,
      );
      expect(
        SelectorCandidateRules.looksAutoGeneratedId(
          'x-550E8400-E29B-41D4-A716-446655440000',
        ),
        isTrue,
      );
    });

    test('long digit runs are auto-generated', () {
      expect(SelectorCandidateRules.looksAutoGeneratedId('ember1234'), isTrue);
      expect(SelectorCandidateRules.looksAutoGeneratedId('id-987654'), isTrue);
    });

    test('long hex runs are auto-generated', () {
      expect(SelectorCandidateRules.looksAutoGeneratedId('a1b2c3d4'), isTrue);
    });

    test('semantic ids are stable', () {
      expect(
        SelectorCandidateRules.looksAutoGeneratedId('orders-link'),
        isFalse,
      );
      expect(SelectorCandidateRules.looksAutoGeneratedId('btnSubmit'), isFalse);
      expect(SelectorCandidateRules.looksAutoGeneratedId('nav2'), isFalse);
    });

    test('empty ids are auto-generated (unusable)', () {
      expect(SelectorCandidateRules.looksAutoGeneratedId(''), isTrue);
      expect(SelectorCandidateRules.looksAutoGeneratedId('  '), isTrue);
    });
  });

  group('SelectorCandidateRules.isUtilityClass', () {
    test('emotion-style css- hash classes', () {
      expect(SelectorCandidateRules.isUtilityClass('css-1abc2de'), isTrue);
    });

    test('hashed suffix classes', () {
      expect(SelectorCandidateRules.isUtilityClass('_3Xy9zAb'), isTrue);
      expect(SelectorCandidateRules.isUtilityClass('foo-1A2b3'), isTrue);
    });

    test('pure hashes with digits', () {
      expect(SelectorCandidateRules.isUtilityClass('e4f5a6'), isTrue);
    });

    test('framework prefixes', () {
      expect(SelectorCandidateRules.isUtilityClass('sc-hash123'), isTrue);
      expect(SelectorCandidateRules.isUtilityClass('jss42'), isTrue);
      expect(SelectorCandidateRules.isUtilityClass('MuiButton-root'), isTrue);
    });

    test('semantic classes are kept', () {
      expect(SelectorCandidateRules.isUtilityClass('menu-orders'), isFalse);
      expect(SelectorCandidateRules.isUtilityClass('btn'), isFalse);
      expect(SelectorCandidateRules.isUtilityClass('order-card'), isFalse);
    });

    test('empty class is utility (unusable)', () {
      expect(SelectorCandidateRules.isUtilityClass(''), isTrue);
    });
  });

  group('SelectorCandidateRules.rankCandidates', () {
    test('ordering: id > data-testid > data-* > tag.class > positional', () {
      final candidates = SelectorCandidateRules.rankCandidates(
        tagName: 'a',
        id: 'orders-link',
        dataAttributes: {'data-testid': 'orders', 'data-track': 'menu'},
        classes: ['menu-orders', 'css-1abc2de'],
        positionalPath: ['div:nth-of-type(1)', 'a:nth-of-type(2)'],
      );
      expect(candidates, [
        '#orders-link',
        '[data-testid="orders"]',
        '[data-track="menu"]',
        'a.menu-orders',
        'div:nth-of-type(1) > a:nth-of-type(2)',
      ]);
    });

    test('auto-generated id is skipped', () {
      final candidates = SelectorCandidateRules.rankCandidates(
        tagName: 'button',
        id: 'ember12345',
        classes: ['submit'],
      );
      expect(candidates, isNot(contains(startsWith('#'))));
      expect(candidates.first, 'button.submit');
    });

    test('data-test preferred after data-testid', () {
      final candidates = SelectorCandidateRules.rankCandidates(
        tagName: 'button',
        dataAttributes: {
          'data-x': '1',
          'data-test': 'save',
          'data-testid': 'save-btn',
        },
      );
      expect(candidates[0], '[data-testid="save-btn"]');
      expect(candidates[1], '[data-test="save"]');
      expect(candidates[2], '[data-x="1"]');
    });

    test('all-utility classes produce no tag.class candidate', () {
      final candidates = SelectorCandidateRules.rankCandidates(
        tagName: 'div',
        classes: ['css-1abc2de', 'sc-foo99'],
      );
      expect(candidates, isEmpty);
    });

    test('positional path limited to 3 levels', () {
      final candidates = SelectorCandidateRules.rankCandidates(
        tagName: 'li',
        positionalPath: [
          'html:nth-of-type(1)',
          'body:nth-of-type(1)',
          'div:nth-of-type(2)',
          'ul:nth-of-type(1)',
          'li:nth-of-type(3)',
        ],
      );
      expect(
        candidates.single,
        'div:nth-of-type(2) > ul:nth-of-type(1) > li:nth-of-type(3)',
      );
    });

    test('no stable signal yields empty list', () {
      expect(SelectorCandidateRules.rankCandidates(tagName: 'span'), isEmpty);
    });
  });

  group('SelectorCandidateRules.normalizeText', () {
    test('trims and collapses whitespace', () {
      expect(
        SelectorCandidateRules.normalizeText('  Siparişlerim\n  detay  '),
        'Siparişlerim detay',
      );
    });

    test('caps at 100 characters', () {
      final long = 'a' * 150;
      expect(SelectorCandidateRules.normalizeText(long).length, 100);
    });
  });
}
