// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: WebUri / sibling-enum (PermissionResourceType, native
// value wire) / external FrameInfo wire glue.
//
// Imports for the external (non-entity) types WebUri and FrameInfo were
// hand-corrected (zuraffa#349: zfa emits a `$` prefix + bogus import for
// types outside lib/src/domain/entities).

import 'package:flutter/foundation.dart';
import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../frame_info/frame_info.dart';
import '../../../web_uri.dart';
import '../enums/index.dart';

part 'permission_request.zorphy.dart';
part 'permission_request.g.dart';

///Class that represents the response used by the [PlatformWebViewCreationParams.onPermissionRequest] event.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $PermissionRequest {
  ///The origin of web content which attempt to access the restricted resources.
  @JsonKey(fromJson: _originFromJson, toJson: _originToJson)
  WebUri? get origin;

  ///List of resources the web content wants to access.
  ///
  ///**NOTE for iOS**: this list will have only 1 element and will be used by the [PermissionResponse.action]
  ///as the resource to consider when applying the corresponding action.
  @JsonKey(
    defaultValue: [],
    fromJson: _resourcesFromJson,
    toJson: _resourcesToJson,
  )
  List<PermissionResourceType>? get resources;

  ///The frame that initiates the request in the web view.
  @JsonKey(fromJson: _frameFromJson, toJson: _frameToJson)
  FrameInfo? get frame;
}

WebUri? _originFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _originToJson(WebUri? value) => value?.toString();

List<PermissionResourceType>? _resourcesFromJson(Object? value) {
  if (value is! List) return null;
  return value
      .map((e) => _resourceTypeFromNative(e))
      .whereType<PermissionResourceType>()
      .toList();
}

Object? _resourcesToJson(List<PermissionResourceType>? resources) =>
    resources?.map(_resourceTypeToNative).toList();

FrameInfo? _frameFromJson(Object? value) => value == null
    ? null
    : FrameInfo.fromJson((value as Map).cast<String, dynamic>());

Object? _frameToJson(FrameInfo? frame) => frame?.toJson();

///PermissionResourceType native values are platform-dependent (the old
///ExchangeableEnum codegen dispatched on `defaultTargetPlatform`): Android
///sends the `android.webkit.resource.*` resource names, iOS/macOS send the
///`WKMediaCaptureType` raw values. These helpers replicate that switch so the
///wire format is unchanged.
PermissionResourceType? _resourceTypeFromNative(Object? value) {
  if (value is int) {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return switch (value) {
          0 => PermissionResourceType.CAMERA,
          1 => PermissionResourceType.MICROPHONE,
          2 => PermissionResourceType.CAMERA_AND_MICROPHONE,
          _ => null,
        };
      default:
        return null;
    }
  }
  if (value is String) {
    switch (value) {
      case 'android.webkit.resource.VIDEO_CAPTURE':
        return PermissionResourceType.CAMERA;
      case 'android.webkit.resource.AUDIO_CAPTURE':
        return PermissionResourceType.MICROPHONE;
      case 'android.webkit.resource.MIDI_SYSEX':
        return PermissionResourceType.MIDI_SYSEX;
      case 'android.webkit.resource.PROTECTED_MEDIA_ID':
        return PermissionResourceType.PROTECTED_MEDIA_ID;
      case 'deviceOrientationAndMotion':
        return PermissionResourceType.DEVICE_ORIENTATION_AND_MOTION;
      default:
        return null;
    }
  }
  return null;
}

Object? _resourceTypeToNative(PermissionResourceType type) {
  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      switch (type) {
        case PermissionResourceType.CAMERA:
          return 'android.webkit.resource.VIDEO_CAPTURE';
        case PermissionResourceType.MICROPHONE:
          return 'android.webkit.resource.AUDIO_CAPTURE';
        case PermissionResourceType.MIDI_SYSEX:
          return 'android.webkit.resource.MIDI_SYSEX';
        case PermissionResourceType.PROTECTED_MEDIA_ID:
          return 'android.webkit.resource.PROTECTED_MEDIA_ID';
        case PermissionResourceType.CAMERA_AND_MICROPHONE:
        case PermissionResourceType.DEVICE_ORIENTATION_AND_MOTION:
          return null;
      }
    case TargetPlatform.iOS:
    case TargetPlatform.macOS:
      switch (type) {
        case PermissionResourceType.CAMERA:
          return 0;
        case PermissionResourceType.MICROPHONE:
          return 1;
        case PermissionResourceType.CAMERA_AND_MICROPHONE:
          return 2;
        case PermissionResourceType.DEVICE_ORIENTATION_AND_MOTION:
          return 'deviceOrientationAndMotion';
        case PermissionResourceType.MIDI_SYSEX:
        case PermissionResourceType.PROTECTED_MEDIA_ID:
          return null;
      }
    default:
      return null;
  }
}
