// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: sibling-enum (PermissionResourceType, native value
// wire) / int-enum (PermissionResponseAction) glue plus the fork's
// constructor defaults (resources = const [], action = DENY).

import 'package:flutter/foundation.dart';
import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'permission_response.zorphy.dart';
part 'permission_response.g.dart';

///Class that represents the response used by the [PlatformWebViewCreationParams.onPermissionRequest] event.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $PermissionResponse {
  ///Resources granted to be accessed by origin.
  ///
  ///**NOTE for iOS**: not used. The [action] taken is based on the [PermissionRequest.resources].
  @JsonKey(
    defaultValue: [],
    fromJson: _resourcesFromJson,
    toJson: _resourcesToJson,
  )
  List<PermissionResourceType>? get resources;

  ///Indicate the [PermissionResponseAction] to take in response of a permission request.
  @JsonKey(
    defaultValue: PermissionResponseAction.DENY,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  PermissionResponseAction? get action;
}

List<PermissionResourceType>? _resourcesFromJson(Object? value) {
  if (value is! List) return null;
  return value
      .map((e) => _resourceTypeFromNative(e))
      .whereType<PermissionResourceType>()
      .toList();
}

Object? _resourcesToJson(List<PermissionResourceType>? resources) =>
    resources?.map(_resourceTypeToNative).toList();

PermissionResponseAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < PermissionResponseAction.values.length
      ? PermissionResponseAction.values[index]
      : null;
}

Object? _actionToJson(PermissionResponseAction? action) => action?.index;

///PermissionResourceType native values are platform-dependent (the old
///ExchangeableEnum codegen dispatched on `defaultTargetPlatform`): Android
///sends the `android.webkit.resource.*` resource names, iOS/macOS send the
///`WKMediaCaptureType` raw values. These helpers replicate that switch so the
///wire format is unchanged.
PermissionResourceType? _resourceTypeFromNative(Object? value) {
  if (value is int) {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return switch (value) {
          0 => PermissionResourceType.CAMERA,
          1 => PermissionResourceType.MICROPHONE,
          2 => PermissionResourceType.CAMERA_AND_MICROPHONE,
          _ => null,
        };
      default:
        return null;
    }
  }
  if (value is String) {
    switch (value) {
      case 'android.webkit.resource.VIDEO_CAPTURE':
        return PermissionResourceType.CAMERA;
      case 'android.webkit.resource.AUDIO_CAPTURE':
        return PermissionResourceType.MICROPHONE;
      case 'android.webkit.resource.MIDI_SYSEX':
        return PermissionResourceType.MIDI_SYSEX;
      case 'android.webkit.resource.PROTECTED_MEDIA_ID':
        return PermissionResourceType.PROTECTED_MEDIA_ID;
      case 'deviceOrientationAndMotion':
        return PermissionResourceType.DEVICE_ORIENTATION_AND_MOTION;
      default:
        return null;
    }
  }
  return null;
}

Object? _resourceTypeToNative(PermissionResourceType type) {
  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      switch (type) {
        case PermissionResourceType.CAMERA:
          return 'android.webkit.resource.VIDEO_CAPTURE';
        case PermissionResourceType.MICROPHONE:
          return 'android.webkit.resource.AUDIO_CAPTURE';
        case PermissionResourceType.MIDI_SYSEX:
          return 'android.webkit.resource.MIDI_SYSEX';
        case PermissionResourceType.PROTECTED_MEDIA_ID:
          return 'android.webkit.resource.PROTECTED_MEDIA_ID';
        case PermissionResourceType.CAMERA_AND_MICROPHONE:
        case PermissionResourceType.DEVICE_ORIENTATION_AND_MOTION:
          return null;
      }
    case TargetPlatform.iOS:
    case TargetPlatform.macOS:
      switch (type) {
        case PermissionResourceType.CAMERA:
          return 0;
        case PermissionResourceType.MICROPHONE:
          return 1;
        case PermissionResourceType.CAMERA_AND_MICROPHONE:
          return 2;
        case PermissionResourceType.DEVICE_ORIENTATION_AND_MOTION:
          return 'deviceOrientationAndMotion';
        case PermissionResourceType.MIDI_SYSEX:
        case PermissionResourceType.PROTECTED_MEDIA_ID:
          return null;
      }
    default:
      return null;
  }
}
